export const ADDINGREDIENT = 'ADDINGREDIENT';
export const REMOVEINGREDIENT = 'REMOVEINGREDIENT';
export const INIT_INGREDIENT = 'INIT_INGREDIENT';
export const FETCH_INGREDIENT_FAILED = 'fetchIngredientFailed';

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDER = 'FETCH_ORDER';
export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';